# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile ResourceCentre_Student/build.xml
    - name: Compile JUnit Test
      run: javac -cp ResourceCentre_Student/bin:ResourceCentre_Student/ant/junit.jar:ResourceCentre_Student/ant/org.hamcrest.core_1.3.0.v201303031735.jar ResourceCentre_Student/test/ResourceCentreTest.java -d ResourceCentre_Student/bin
    - name: Run JUnit test
      run: java -cp ResourceCentre_Student/bin:ResourceCentre_Student/ant/junit.jar:ResourceCentre_Student/ant/org.hamcrest.core_1.3.0.v201303031735.jar org.junit.runner.JUnitCore ResourceCentreTest
    - name: Test Execution
      run: java -cp ResourceCentre_Student/bin ResourceCentre < ResourceCentre_Student/user_input.txt
